### ISSUE TITLE
Framework upgrade

### ISSUE THREAD

**Issue by siaw23** [berkmancenter/tagteam#27]
Is there a reason why `tagteam` is still running `rails 3.2`. I believe the current security fixes in the current release of `rails` outweigh the reasons why `tagteam` should still be running on be an older version of `rails`. I am not sure yet but strong parameters in `rails 4.2` alone sounds like a good compromise. Also the code in the models and controllers are cluttered. We could clean things up by thinking more of a domain-driven development and introduce micro-services than what we currently have on this project. Just my two cents. I could help on the project if need be.

Moreover, if the future of this project is going to have subscription to feeds as a major feature, then I think `Action Cable` in `rails 5` could be something we might want to be thinking about now.

**Comment by jsdiaz** [comment]
We are doing this currently - the rails 5 version of the app is in testing. You can check out the code on the dev branch if you are curious. We're always up for help - we have a large list of internal issues if you are still interested.

Thanks!
