### ISSUE TITLE
"Automatically approve .edu signups" feature should be a configuration option

### ISSUE THREAD

**Issue by zackw** [berkmancenter/tagteam#38]
If I'm reading `models/user.rb` correctly, the policy of automatically approving new user accounts if they have `.edu` email addresses is hardwired into the code.  Please make it possible to turn this off as a configuration option.  Or perhaps we could configure a regular expression matching user email addresses to auto-approve?  With the empty string meaning "nobody gets auto-approved" and a wildcard regex for "everyone".

**Comment by jsdiaz** [comment]
Zack, this is a feature in release 2.1.0.6. Glad to know there is external interest for this.
